### ISSUE TITLE
Technical debt in NodeJS Mentoring Program.  

### ISSUE THREAD

**Issue by kayarmolenka** [kayarmolenka/nodejs-global-mentoring-program-2022#4]
- [x] Make change to `fill-in-db-users.ts` file

- [x] Learn theory about (`Promises`, `EventLoop`, `Async/Await` in NodeJS )

**Comment by Taximu** [comment]
Not just learn, understand theory and apply in practical tasks.

**Comment by kayarmolenka** [comment]
Done.

**Comment by kayarmolenka** [comment]
Everything is OK. Done!
